version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: 
      context: ./api
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "5555:5000"
    depends_on:
      mysql:
        condition: service_started
    restart: on-failure
    command: sh -c "sleep 10 && node index.mjs"

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8954:8954"
    depends_on:
      - backend

volumes:
  mysql-data: